[theme]
base                     = "light"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#F6F6F4"
textColor                = "#111111"
primaryColor             = "#D8412F"
font                     = "sans serif"
